import { SystemOptions, FontStyleOptions } from '../types';

export const defaultBaseFont: FontStyleOptions = {
  family: 'Tahoma',
  color: '#FFFFFF',
  bold: false,
  italic: false,
  underline: false,
  superscript: false,
  subscript: false,
  alignHorizontal: 'center',
  alignVertical: 'middle',
  maxSize: 90,
  opacity: 100,
  outlineEnabled: true,
  outlineColor: '#000000',
  outlineSize: 3,
  shadowEnabled: true,
  shadowColor: '#000000',
  shadowBlur: 4,
  shadowOffset: 2,
  marginLeft: 0,
  marginTop: 0,
  marginRight: 0,
  marginBottom: 0,
  casing: 'none',
  lineSpacing: 1.35,
};

export const defaultSystemOptions: SystemOptions = {
  mainOutput: {
    general: {
      outputMonitor: 'Monitor 1 (Secondary)',
      alphaChannel: 'Disabled',
      position: { left: 1920, top: 0, width: 1920, height: 1080 },
      margins: { left: 0, top: 0, right: 0, bottom: 0 },
      defaultFont: { ...defaultBaseFont },
      disableLogoOnLive: false,
    },
    song: {
      songFont: { ...defaultBaseFont, maxSize: 90, alignHorizontal: 'center', bold: false },
      showVerseChorusLabel: true,
      labelFont: { ...defaultBaseFont, maxSize: 42, color: '#67E8F9', bold: true, alignHorizontal: 'left' },
      labelLocation: 'Header',
      labelStyle: 'uppercase',
      labelPrefix: '',
      displayCopyrightInfo: true,
      copyrightFont: { ...defaultBaseFont, maxSize: 24, color: '#A0AEC0', bold: false, alignHorizontal: 'left' },
      copyrightPosition: 'Bottom Left',
      licenseInfo: 'CCLI License #1234567',
      showOnFirstSlideOnly: false,
      showOnLastSlideOnly: false,
      minFontSize: 24,
      allCapsLyrics: false,
      lineSpacing: 1.35,
      margins: { left: 0, top: 0, right: 0, bottom: 0 },
      autoAdjust: true,
      breakOnNewVerse: true,
      automaticallyFlow: true,
      maxLinesPerSlide: 4,
      splitLongSections: true,
      splitLabelStyle: 'part',
    },
    scripture: {
      enableScriptureSupport: true,
      scriptureFont: { ...defaultBaseFont, maxSize: 90, family: 'Tahoma', bold: false },
      showVerseNumbers: true,
      verseFont: { ...defaultBaseFont, maxSize: 28, color: '#F6E05E', bold: true },
      verseNumberStyle: 'superscript',
      verseColor: '#F6E05E',
      showReference: true,
      referenceFont: { ...defaultBaseFont, maxSize: 22, color: '#E2E8F0', bold: true },
      referenceLocation: 'After Each Slide',
      referenceFormat: 'Book Chapter:Verse (Translation)',
      referenceCasing: 'none',
      showTranslationBadge: true,
      referencePrefix: '',
      referenceSuffix: '',
      showBookName: true,
      showChapterNumber: true,
      showVerseRangeInRef: true,
      showCompletePassage: false,
      referenceIndent: true,
      abbreviateBookNames: false,
      additionalLineSpacing: false,
      showReferenceOnly: false,
      breakOnNewVerse: false,
      automaticallyFlow: true,
      minFontSize: 24,
      lineSpacing: 1.35,
      margins: { left: 0, top: 0, right: 0, bottom: 0 },
      autoAdjust: true,
    },
    presentations: {
      titleFont: { ...defaultBaseFont, maxSize: 90, bold: true },
      subTitleFont: { ...defaultBaseFont, maxSize: 48, italic: true },
      contentFont: { ...defaultBaseFont, maxSize: 90 },
    },
    transitions: {
      activeTab: 'Slide',
      blend: 'Blend',
      duration: 500,
      easing: 'easeInOut',
    },
    alerts: {
      nursery: {
        enabled: true,
        font: { ...defaultBaseFont, maxSize: 32, bold: true, color: '#FFFFFF' },
        backgroundColor: '#FF0000',
        backgroundOpacity: 100,
        location: 'Top Right',
        autoRemove: true,
        autoRemoveDuration: '01:00',
        currentCode: '',
      },
      message: {
        enabled: true,
        font: { ...defaultBaseFont, maxSize: 42, bold: true, color: '#FFFFFF' },
        backgroundColor: '#FF0000',
        backgroundOpacity: 100,
        location: 'Bottom',
        scrollSpeed: 5,
        currentMessage: '',
      },
    },
  },
  alternateOutput: {
    enabled: false,
    outputMonitor: 'Monitor 2',
    position: { left: 0, top: 0, width: 1920, height: 1080 },
    margins: { left: 0, top: 0, right: 0, bottom: 0 },
    defaultFont: { ...defaultBaseFont },
  },
  foldback: {
    enabled: true,
    outputMonitor: 'Monitor 3 (Stage)',
    position: { left: 0, top: 0, width: 1920, height: 1080 },
    margins: { left: 0, top: 0, right: 0, bottom: 0 },
    defaultFont: { ...defaultBaseFont, family: 'Segoe UI', color: '#E2E8F0' },
    clockEnabled: true,
  },
  serviceIntervals: {
    countdownEnabled: true,
    countdownTime: '05:00',
    intervalType: 'Pre-Service Countdown',
    showOnMainDisplay: false,
    backgroundAssetId: '',
  },
  slideLabels: [
    { id: '1', name: 'CHORUS', bgColor: '#58243A', textColor: '#FFFFFF', shortcut: 'C' },
    { id: '2', name: 'END', bgColor: '#1A2456', textColor: '#FFFFFF', shortcut: 'E, NUM .' },
    { id: '3', name: 'ENDING', bgColor: '#541A1A', textColor: '#FFFFFF', shortcut: 'E, NUM .' },
    { id: '4', name: 'INTERLUDE', bgColor: '#1D3B6D', textColor: '#FFFFFF', shortcut: 'I' },
    { id: '5', name: 'INTRO', bgColor: '#1F4735', textColor: '#FFFFFF', shortcut: 'I' },
    { id: '6', name: 'INTRODUCTION', bgColor: '#1F4735', textColor: '#FFFFFF', shortcut: 'I' },
    { id: '7', name: 'MISC', bgColor: '#254070', textColor: '#FFFFFF', shortcut: 'M' },
    { id: '8', name: 'PRE-CHORUS', bgColor: '#4A2840', textColor: '#FFFFFF', shortcut: 'R' },
    { id: '9', name: 'SLIDE', bgColor: '#223862', textColor: '#FFFFFF', shortcut: 'S' },
    { id: '10', name: 'TAG', bgColor: '#4A1D54', textColor: '#FFFFFF', shortcut: 'T, NUM .' },
    { id: '11', name: 'VAMP', bgColor: '#233966', textColor: '#FFFFFF', shortcut: 'V' },
    { id: '12', name: 'VERSE', bgColor: '#264273', textColor: '#FFFFFF', shortcut: 'V' },
    { id: '13', name: '<EMPTY>', bgColor: '#1E222D', textColor: '#99A1B3', shortcut: 'None' },
    { id: '14', name: '<OTHER>', bgColor: '#273F6C', textColor: '#FFFFFF', shortcut: '' },
  ],
  appearance: {
    themeMode: 'dark',
    accentColor: 'cyan',
    compactMode: false,
    highContrast: false,
  },
  advanced: {
    showLiveOnStartup: true,
    advanceScheduleOnGoLive: true,
    preventDvdSpinDown: false,
    alwaysSaveStandalone: false,
    enableRemoteControl: true,
    remoteName: 'SimpleWorship Remote (DESKTOP-4LFFO1V)',
  },
};
